// import './styles/index'
export { default as Button } from './button'
export { default as Switch } from './switch'
export { default as Icon } from './icon'
export { default as Spin } from './spin'
export { default as Audio } from './audio'
